# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7626cd836909474711d41fc56b497aabf00395b0f0451b207e20dbe7c006f679f3aa42d97d06806a1afb4958982a1599afb6aad070153fb84ef9b5e848a2e05e

test:
  secret_key_base: 8059006774350424c7f473dab11496be72971c20e6f4ab33a91c325041d9fe7ba36ff5e9197d25c027db06531df52eca452213a8783a76eb575a103df8b39276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
